{
 "title": "Windows Exporter Dashboard",
 "description": "Windows monitoring dashboard for Prometheus with comprehensive resource overview and detailed metrics. Compatible with windows_exporter 0.31.1+ and optimized for Grafana v12+.",
 "tags": [
  "Prometheus",
  "windows_exporter",
  "windows",
  "monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(windows_os_hostname,job)"
    }
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(windows_os_hostname{job=~\"$job\"},hostname)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(windows_os_hostname{job=~\"$job\", hostname=~\"$hostname\"},instance)"
    }
   },
   {
    "name": "show_hostname",
    "label": "Display Hostname",
    "query": {
     "query": "label_values(windows_os_hostname{job=~\"$job\", instance=~\"$instance\"},hostname)"
    }
   },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values(windows_os_hostname,location)"
    }
   },
   {
    "name": "ipadd",
    "label": "IP Address",
    "query": {
     "query": "label_values(windows_net_nic_address_info{job=\"$job\", instance=\"$instance\"},address)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource Overview ($job) - Selected Host: [$show_hostname] Instance: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "$job: Server Resource Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_os_info{job=~\"$job\"}*on(instance)group_right(fqdn,product)(windows_os_hostname{job=~\"$job\"}*on(instance)group_right(hostname,family,nic)(windows_net_nic_address_info{job=~\"$job\",nic!~\"isatap.*|Teredo Tunneling Pseudo-Interface|Microsoft Wi-Fi Direct Virtual Adapter|Bluetooth Device.*|Microsoft Hyper-V Network Adapter|VirtualBox.*|VMware.*|Loopback.*\",address!~\"127.*|169.*|fe80.*\"}))"
    },
    {
     "expr": "time() - windows_system_boot_time_timestamp{job=~\"$job\"}",
     "legendFormat": "Uptime"
    },
    {
     "expr": "windows_cpu_logical_processor{job=~\"$job\"} - 0",
     "legendFormat": "CPU Cores"
    },
    {
     "expr": "avg by (instance) (windows_cpu_core_frequency_mhz{job=~\"$job\"})",
     "legendFormat": "CPU Frequency"
    },
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "windows_memory_physical_total_bytes{job=~\"$job\"} - 0",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "100 - 100 * windows_memory_physical_free_bytes{job=~\"$job\"} / windows_memory_physical_total_bytes{job=~\"$job\"}",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "1 - (windows_logical_disk_free_bytes{job=~\"$job\",volume=~\"C:\"}/windows_logical_disk_size_bytes{job=~\"$job\",volume=~\"C:\"})",
     "legendFormat": "C: Drive Usage"
    },
    {
     "expr": "max by (instance) (1-windows_logical_disk_free_bytes{job=~\"$job\"}/windows_logical_disk_size_bytes{job=~\"$job\"})"
    },
    {
     "expr": "sum by (instance) (windows_system_processes{job=~\"$job\"})"
    },
    {
     "expr": "sum by (instance) (windows_service_state{job=~\"$job\",state=~\"running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Host",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100.0 - 100 * windows_memory_physical_free_bytes{job=~\"$job\"} / windows_memory_physical_total_bytes{job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Details by Host (Max Traffic NIC)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "max by (instance) (irate(windows_net_bytes_sent_total{job=~\"$job\",nic!~'isatap.*|VPN.*'}[2m]))*8",
     "legendFormat": "{{instance}}_Upload"
    },
    {
     "expr": "-max by (instance) (irate(windows_net_bytes_received_total{job=~\"$job\",nic!~'isatap.*|VPN.*'}[2m]))*8",
     "legendFormat": "{{instance}}_Download"
    }
   ]
  },
  {
   "title": "Disk I/O Details by Host (Max Activity)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-max by (instance) (irate(windows_logical_disk_read_bytes_total[2m]))",
     "legendFormat": "{{instance}}_Read"
    },
    {
     "expr": "max by (instance) (irate(windows_logical_disk_write_bytes_total[2m]))",
     "legendFormat": "{{instance}}_Write"
    }
   ]
  },
  {
   "title": "Disk I/O Details by Host (Max Activity)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "-max by (instance) (irate(windows_logical_disk_reads_total[2m]))",
     "legendFormat": "{{instance}}_Read"
    },
    {
     "expr": "max by (instance) (irate(windows_logical_disk_writes_total[2m]))",
     "legendFormat": "{{instance}}_Write"
    }
   ]
  },
  {
   "title": "Resource Details [$show_hostname: $instance] $ipadd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "Boot Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - windows_system_boot_time_timestamp{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(windows_cpu_time_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[2m])))*100"
    }
   ]
  },
  {
   "title": "Partition Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (\n  windows_logical_disk_free_bytes{job=~\"$job\",instance=~\"$instance\",volume!~\"HarddiskVolume.*\"} \n  / \n  windows_logical_disk_size_bytes{job=~\"$job\",instance=~\"$instance\",volume!~\"HarddiskVolume.*\"}\n) * 100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(windows_service_state{job=~\"$job\",instance=~\"$instance\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Process Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_system_processes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Process Count"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "windows_cpu_logical_processor{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_memory_physical_free_bytes{job=~\"$job\",instance=~\"$instance\"} / windows_memory_physical_total_bytes{job=~\"$job\",instance=~\"$instance\"})*100"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "windows_memory_physical_total_bytes{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - avg(irate(windows_cpu_time_total{job=~\"$job\",instance=~\"$instance\",mode=\"idle\"}[5m]))*100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_memory_physical_total_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Total Physical Memory"
    },
    {
     "expr": "windows_memory_physical_free_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Free Physical Memory"
    },
    {
     "expr": "windows_memory_commit_limit{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Virtual memory"
    },
    {
     "expr": "windows_memory_committed_bytes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Free virtual memory"
    }
   ]
  },
  {
   "title": "Disk Free Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{job=~\"$job\",instance=~\"$instance\",volume!~\"HarddiskVolume.*\"}",
     "legendFormat": "Free Space {{volume}}"
    },
    {
     "expr": "windows_logical_disk_size_bytes{job=~\"$job\",instance=~\"$instance\",volume!~\"HarddiskVolume.*\"}",
     "legendFormat": "Total Space {{volume}}"
    }
   ]
  },
  {
   "title": "Network Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(windows_net_bytes_received_total{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m])*8",
     "legendFormat": "{{nic}}-Received-Download"
    },
    {
     "expr": "irate(windows_net_bytes_sent_total{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m])*8 > 0",
     "legendFormat": "{{nic}}-Sent-Upload"
    }
   ]
  },
  {
   "title": "Disk Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(windows_logical_disk_read_bytes_total{job=~\"$job\",instance=~\"$instance\",volume!~\"HarddiskVolume.*\"}[5m])",
     "legendFormat": "read {{volume}}"
    },
    {
     "expr": "irate(windows_logical_disk_write_bytes_total{job=~\"$job\",instance=~\"$instance\",volume!~\"HarddiskVolume.*\"}[5m])",
     "legendFormat": "write {{volume}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(windows_logical_disk_reads_total{job=~\"$job\",instance=~\"$instance\",volume!~\"HarddiskVolume.*\"}[5m])",
     "legendFormat": "read {{volume}}"
    },
    {
     "expr": "irate(windows_logical_disk_writes_total{job=~\"$job\",instance=~\"$instance\",volume!~\"HarddiskVolume.*\"}[5m])",
     "legendFormat": "write {{volume}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(instance,nic)(irate(windows_net_bytes_total{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}[5m])*8)/on(instance,nic)group_left()(windows_net_current_bandwidth_bytes{job=~\"$job\",instance=~\"$instance\",nic!~'isatap.*|VPN.*'}*8))*100",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Network discarded/error packets",
   "type": "timeseries",
   "description": "Network discarded/error packets",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 38 },
   "targets": [
    {
     "expr": "irate(windows_net_packets_received_discarded_total{job=~\"$job\",instance=~\"$instance\", nic!~'isatap.*|VPN.*'}[5m]) + irate(windows_net_packets_received_errors_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{nic}} outbound"
    },
    {
     "expr": "irate(windows_net_packets_outbound_discarded_total{job=~\"$job\",instance=~\"$instance\", nic!~'isatap.*|VPN.*'}[5m]) + irate(windows_net_packets_outbound_errors_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{nic}} received"
    }
   ]
  },
  {
   "title": "System Threads",
   "type": "timeseries",
   "description": "System Threads",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "windows_system_threads{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "system_threads"
    }
   ]
  },
  {
   "title": "System Exception Dispatches",
   "type": "timeseries",
   "description": "System Exception Dispatches",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 38 },
   "targets": [
    {
     "expr": "irate(windows_system_exception_dispatches_total{job=~\"$job\",instance=~\"$instance\"}[5m])",
     "legendFormat": "exceptions"
    }
   ]
  }
 ]
}