---
prometheus_config:
  global:
    scrape_interval: 30s
    scrape_timeout: 30s
  scrape_configs:
    - job_name: "prometheus"
      static_configs:
        - targets: ["localhost:9090"]
          labels:
            environment: "hetzner"
            customer: "ruso.dev"
    - job_name: "node_exporter"
      static_configs:
        - targets:
            - "nbg-01:9100"
          labels:
            environment: "hetzner"
            customer: "ruso.dev"
        - targets:
            - "px1:9100"
            - "px2:9100"
            - "px3:9100"
          labels:
            environment: "homelab"
            customer: "ruso.dev"
    - job_name: "pve_exporter"
      metrics_path: /pve
      static_configs:
        - targets:
            - "px1:9221"
            - "px2:9221"
            - "px3:9221"
          labels:
            environment: "homelab"
            customer: "ruso.dev"
            service: "pve"
    - job_name: "windows_exporter"
      scheme: https
      metrics_path: /metrics
      static_configs:
        - targets:
            - "rus-pc.bombay-tuna.ts.net"
          labels:
            environment: "personal"
            customer: "ruso.dev"
            service: "windows"
        - targets:
            - "rus-win.bombay-tuna.ts.net"
          labels:
            environment: "personal"
            customer: "ruso.dev"
            service: "windows"
    - job_name: "blackbox_exporter"
      static_configs:
        - targets: ["nbg-01:9115"]
          labels:
            environment: "hetzner"
            customer: "ruso.dev"
            service: "blackbox_exporter"
    - job_name: "smokeping_prober"
      static_configs:
        - targets: ["nbg-01:9374"]
    - job_name: "probe/homelab/proxmox-probing"
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
            - "https://px1.bombay-tuna.ts.net"
            - "https://px2.bombay-tuna.ts.net"
            - "https://px3.bombay-tuna.ts.net"
          labels:
            environment: "homelab"
            customer: "ruso.dev"
            service: "proxmox"
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: "nbg-01:9115"
