---
prometheus_version: "v2.54.1"
prometheus_latest: false
prometheus_listen: ":9090"
prometheus_data_dir: "/var/lib/prometheus"
prometheus_config_dir: "/etc/prometheus"
prometheus_config_path: "{{ prometheus_config_dir }}/prometheus.yml"
prometheus_service_path: "/etc/systemd/system/prometheus.service"
prometheus_config:
  global:
    scrape_interval: 15s
  scrape_configs:
    - job_name: "prometheus"
      static_configs:
        - targets: ["localhost:9090"]
    - job_name: "node_exporter"
      static_configs:
        - targets: ["localhost:9100"]
