tailscale_auth_key: ENC[AES256_GCM,data:L1u5YAGfrQSTBjxk4VR51etwg2VrBynrXtmLKjv+p2B8WlFSEIBfnTQiJ84UPogy2yagIzK8fRXnfMPSjxs=,iv:FR8Up+4v0Of5tFE+F1NyjIDIDsbekRpwCgJ1Nvw0LW0=,tag:ciQ3mrTsymAm8SAbC7w8uA==,type:str]
sops:
  age:
    - recipient: age1mwsp9vznduxqxwsvva45htct25wartlsj707qyuz3fydt9tjnqdq5zfucs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VFNpNFRFeWE5NktvckxJ
        amJ0dEk2bWZOaWpWby9XVjlFdGE5djNUUERNCld4SWlWWnpJMnpXcE9KUDcwS2o3
        c1ZLVHplY2pmSWV3aWFBVWIyZy9FOFkKLS0tIGw2ckNiMUtDM3pOVjVNZ3RPRmhS
        STRwWFJTTkkzTkRsRnhrRVNEUElrbzgKGtQX76QkDAwV8asdmpEy867vAhty9rt9
        JpW3z4M8F+bQy9pbtHtCVWy8MaE/2lpJRICzxilBfJwV4WYksEcr5Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1q0slmzl2tt9pv44f3pq5j5j3vnvgm2u5df3gzcrmsp77r69arpaskfz83s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKM0tDayt1bFgzeXJoRUwr
        SThMWUJJS2JnUWlaZHhZVFduK0dPcWV5MmlRCmFOM2ltUFY2YmNkcm9MbkhpRWQ5
        dVpjU0tGeXV2SmpIWVgzekxrSldLQncKLS0tIFpXNWhCRnFGREtFSFQyalVmd3FZ
        WDFKZVJOeEpFODBGRnJaQXRKc2tZN2cKuaVNZLK8qKyxBg43yTsZHt3sW9C9sRBv
        2sjW2koP9eQBJE1l4YX9ds2e+qwOKnt66nTRz5dAvr9ZoxiNnA+DJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-16T15:36:28Z"
  mac: ENC[AES256_GCM,data:BrBeIB6G1gEUtPAF+dOnhHk3w5yQ7oqFsAYOQRv8ofH2XVvh4TSbp7Aaqvdwgry68eTcTLm8aNB2BTK9eVyjHf5c020wynNL3cbrn/je1fvRYuyBPRxNG0oMAdqfNczDdIEn5DdoQBlOt+6FOhPj8RRFGm4N7Xn7NwomKoK5tMU=,iv:1RktKSiUIS8hMy4JNYgcnqkzSGw8o2HmV9lqv83EsA8=,tag:8N0WG7WYGRU1X1gONBZFSg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
