---
- name: Install ufw
  package:
    name: ufw
    state: present
  become: true

- name: Reset UFW to clean state
  ufw:
    state: reset
  become: true
  when: firewall_reset | default(false)

- name: Configure UFW policy
  ufw:
    state: "{{ firewall_state }}"
    policy: "{{ firewall_policy }}"
    direction: "{{ firewall_policy_direction }}"
  become: true

- name: Configure UFW rules (declarative)
  ufw:
    rule: "{{ item.rule | default('allow') }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.proto | default('tcp') }}"
    src: "{{ item.src | default(omit) }}"
    interface: "{{ item.interface | default(omit) }}"
    direction: "{{ item.direction | default('in') }}"
  become: true
  loop: "{{ firewall_rules }}"
  notify: reload firewall

- name: Enable UFW
  ufw:
    state: enabled
  become: true
  when: firewall_state == 'enabled'