---
- name: Remove Node Exporter
  hosts: all
  become: true
  vars:
    confirm_remove: false
  tasks:
    - name: Check if service exists
      ansible.builtin.service_facts:

    - name: Fail if removal is not confirmed
      ansible.builtin.meta: end_play
      when: not confirm_remove

    - name: Stop and disable service
      ansible.builtin.systemd:
        name: node_exporter
        state: stopped
        enabled: false
      when: "'node_exporter.service' in ansible_facts.services"
      failed_when: false

    - name: Remove files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/local/bin/node_exporter
        - /etc/systemd/system/node_exporter.service

    - name: Remove user and group
      ansible.builtin.user:
        name: node_exporter
        state: absent
        remove: true
      failed_when: false

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true
