- name: Remove Blackbox Exporter
  hosts: all
  become: true
  vars:
    confirm_remove: false
  tasks:
    - name: Check if service exists
      ansible.builtin.service_facts:

    - name: Fail if removal is not confirmed
      ansible.builtin.meta: end_play
      when: not confirm_remove

    - name: Stop and disable service
      ansible.builtin.systemd:
        name: blackbox_exporter
        state: stopped
        enabled: false
      when: "'blackbox_exporter.service' in ansible_facts.services"
      failed_when: false

    - name: Remove files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/blackbox.yml
        - /usr/local/bin/blackbox_exporter
        - /etc/systemd/system/blackbox_exporter.service

    - name: Remove user and group
      ansible.builtin.user:
        name: blackbox_exporter
        state: absent
        remove: true
      failed_when: false

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true
