---
- name: Remove Prometheus
  hosts: all
  become: true
  vars:
    confirm_remove: false
  tasks:
    - name: Check if service exists
      ansible.builtin.service_facts:

    - name: Fail if removal is not confirmed
      ansible.builtin.meta: end_play
      when: not confirm_remove

    - name: Stop and disable service
      ansible.builtin.systemd:
        name: prometheus
        state: stopped
        enabled: false
      when: "'prometheus.service' in ansible_facts.services"
      failed_when: false

    - name: Remove files and directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/local/bin/prometheus
        - /usr/local/bin/promtool
        - /etc/systemd/system/prometheus.service
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Remove user and group
      ansible.builtin.user:
        name: prometheus
        state: absent
        remove: true
      failed_when: false

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true
