- name: Remove PVE Exporter
  hosts: all
  become: true
  vars:
    confirm_remove: false
  tasks:
    - name: Check if service exists
      ansible.builtin.service_facts:

    - name: Fail if removal is not confirmed
      ansible.builtin.meta: end_play
      when: not confirm_remove

    - name: Stop and disable service
      ansible.builtin.systemd:
        name: pve_exporter
        state: stopped
        enabled: false
      when: "'pve_exporter.service' in ansible_facts.services"
      failed_when: false

    - name: Remove files and directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/pve_exporter.yml
        - /etc/systemd/system/pve_exporter.service
        - /usr/local/bin/pve_exporter
        - /opt/pve_exporter

    - name: Remove user and group
      ansible.builtin.user:
        name: pve_exporter
        state: absent
        remove: true
      failed_when: false

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true
