- hosts: all
  become: true
  vars:
    confirm_remove: false
  tasks:
    - ansible.builtin.service_facts:
    - ansible.builtin.meta: end_play
      when: not confirm_remove
    - ansible.builtin.systemd:
        name: blackbox_exporter
        state: stopped
        enabled: false
      when: "'blackbox_exporter.service' in ansible_facts.services"
      failed_when: false
    - ansible.builtin.file:
        path: /etc/blackbox.yml
        state: absent
    - ansible.builtin.file:
        path: /usr/local/bin/blackbox_exporter
        state: absent
    - ansible.builtin.file:
        path: /etc/systemd/system/blackbox_exporter.service
        state: absent
    - ansible.builtin.systemd:
        daemon_reload: true

    - name: Remove user
      ansmble.builtin.user:
        name: blackbox_exporter
        state: absent
        remove: true
