#!/bin/bash

if [ $# -lt 1 ]; then
  echo "Usage: sshr <hostname>"
  exit 1
fi

HOST=$1
PASSWORD=$(pass rs/vrz0506)

if [ -z "$PASSWORD" ]; then
  echo "Error: It was not possible to get the password from pass"
  exit 1
fi

sshpass -p "$PASSWORD" ssh -t "$HOST" $2
