apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io
  chart: cilium
  version: "1.17.1"
  targetNamespace: kube-system
  valuesContent: |-
    ipam:
      mode: "kubernetes"

    kubeProxyReplacement: "strict"
    k8sServiceHost: "192.168.1.103"
    k8sServicePort: 6443

    tunnel: "disabled"

    ipv4NativeRoutingCIDR: "10.42.0.0/16"

    cni:
      binPath: "/var/lib/rancher/k3s/data/current/bin"
      confPath: "/var/lib/rancher/k3s/agent/etc/cni/net.d"
