apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io
  chart: cilium
  version: "1.17.1"
  targetNamespace: kube-system
  valuesContent: |-
    bpf:
      lbExternalClusterIP: true
      masquerade: true
      vlanBypass:
        - ""
    envoy:
      enabled: false
    externalIPs:
      enabled: false
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
    ingressController:
      enabled: false
      loadbalancerMode: dedicated
    ipam:
      mode: kubernetes
      operator:
        clusterPoolIPv4PodCIDRList: 10.42.0.0/16
    nodePort:
      enabled: true
    socketLB:
      enabled: true
