apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io
  chart: cilium
  version: "1.17.1"
  targetNamespace: kube-system
  valuesContent: |-
    kubeProxyReplacement: true
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList: 10.42.0.0/16
    socketLB:
      enabled: false
    envoy:
      enabled: false
    externalIPs:
      enabled: false
    gatewayAPI:
      enabled: false
    hubble:
      relay:
        enabled: false
      ui:
        enabled: false
    nodePort:
      enabled: true
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: lb-pool
spec:
  blocks:
    - cidr: 192.168.1.224/29
