---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: kube-system
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgCCTIA69jkHWLQtFWft28kELTWgYbc9KmCbkFe7qui4hviA6tVcEsIJID7IXEnJvCiq1Hkle2ICU5v8uc44vyLEV37vHp+EH7bUhnkjwkmfVA3rN6BcFiPYjJ9etP6iQneiPqJEdT2HXEyS6jLBAFzgd3TNmdIXGq3Mwdi5SKddkAWpZ4+YTjACdxeoA1Av9rNEfbsW3N2lyRV97zfbQbNFqciNNtEBZa/jSJIw/keePv2otGMHnYDcC+rqCLA+mKkkfAzeJhVVmAnD5aD1gevxDD9zvHgkd/+Cse8sQEDqV4BhKyZu8W/NVvaTJO3pcTNRf7OVldm3UGfjIvMIXI0XRJtMKE3KBq0by/GHVXDj88EDf9C0IuLuhnZ1ljp4Hzs/4gg3uhgSnJRa7ym4JpDnqZCEonfgHYj6Ht0gmgAwA+Y+jEaN1AwAL1Fx6sEi8mXAyzNbExms9gP2vcdA3QYBmhVqBZpZGCB+b0SD4BQA0bWTEp7UdRIG8HvZC6A6ldY0vVqKtApaguk2CBgMHUugnt4Ci49BUK013g2JpP/bgSg5LGy/g3CHrtIR4baax/N7eRwBjZ65+fNikNrm0HFxp5fMYkAWQgYAYTOgKUQbX6b9IZxVXA51pBUQjiZkxJn3KgjsPMoLLpv05WcMXpSAJa4wpBYZ5u3kaPrp6E/dvw2008T774R+qCDg7w9AhsZ1rsqqPDgc641VRwacvTiCOPrIIhKKSCz00GuOM0SseScysH8Vkqnq
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: kube-system
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns
  namespace: kube-system
spec:
  schedule: "*/5 * * * *" # Ejecuta cada 5 minutos
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cloudflare-ddns
              image: favonia/cloudflare-ddns:latest
              env:
                - name: CLOUDFLARE_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare-api-token
                      key: CLOUDFLARE_API_TOKEN
                - name: DOMAINS
                  value: "ddns.ruso.dev"
                - name: PROXIED
                  value: "false"
                - name: UPDATE_CRON
                  value: "@once"
          restartPolicy: OnFailure
