apiVersion: v1
kind: Namespace
metadata:
  name: kyverno

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kyverno
  namespace: kube-system
spec:
  repo: https://kyverno.github.io/kyverno
  chart: kyverno
  version: 3.3.7
  targetNamespace: kyverno
