apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system

---
# We need to first install the Longhorn Helm chart manually first, because HelmChart CRDs requrie a CSI driver to be installed first.
# then we can configure the Longhorn Helm chart to use this approach
# helm repo add longhorn https://charts.longhorn.io
# helm repo update
# helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace --version 1.8.1
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: kube-system
spec:
  repo: https://charts.longhorn.io
  chart: longhorn
  version: 1.8.1
  targetNamespace: longhorn-system
